AWSTemplateFormatVersion: "2010-09-09"
Description: Flow logs for networking resources

Parameters:
  VpcId:
    Type: String
    Description: The VPC to create flow logs for

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: LogGroup

  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Effect: Allow
                Resource: "*"

  FlowLog:
    Type: AWS::EC2::FlowLog
    DependsOn: LogGroup
    Properties:
      DeliverLogsPermissionArn: !GetAtt IamRole.Arn
      LogGroupName: LogGroup
      ResourceId: !Ref VpcId
      ResourceType: VPC
      TrafficType: ALL
