AWSTemplateFormatVersion: "2010-09-09"

Description: Create NAT Gateway and associated route.

Parameters:
  PublicSubnetId:
    Description: Public Subnet ID to add the NAT Gateway to
    Type: AWS::EC2::Subnet::Id
  RouteTableId:
    Description: The private subnet route table to add the NAT Gateway route to
    Type: String

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnetId

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTableId
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
